import type { PermissionKey } from "~/modules/role/domain/permission-definitions";

/** 4 role mặc định — permissions tái tạo đúng hành vi trước khi tách nhỏ
 * `.action` (xem `~/modules/role/domain/permission-definitions.ts`), cộng 2
 * điều chỉnh đã chốt: role "user" được cấp đủ 4 hành động của `don-hang` để
 * không phá luồng thanh toán/huỷ/xoá món/khuyến mãi ở goi-mon (nhân viên phục
 * vụ dùng hằng ngày), "viewer" giữ nguyên chỉ toàn `.get`.
 *
 * File data thuần (không side-effect gì khi import) — dùng chung bởi
 * `seed-roles.ts` (tạo role còn thiếu, không đụng role đã có) và
 * `resync-default-roles.ts` (ghi đè lại ĐÚNG 4 role mặc định này về permission
 * chuẩn, dùng 1 lần sau khi đổi tên permission key — xem file đó). */
export const SEED_ROLES: { name: string; description: string; permissions: PermissionKey[] }[] = [
  {
    name: "user",
    description: "Nhân viên phục vụ — dùng màn hình gọi món tại bàn.",
    permissions: [
      "don-hang.thanh-toan",
      "don-hang.huy",
      "don-hang.xoa-mon",
      "don-hang.khuyen-mai",
    ],
  },
  {
    name: "viewer",
    description: "Chỉ xem — không thao tác được ở bất kỳ trang quản lý nào.",
    permissions: [
      "dashboard.get",
      "mon-an.get",
      "ban.get",
      "don-hang.get",
      "khuyen-mai.get",
      "ca-lam-viec.get",
      "may-in.get",
      "thanh-toan.get",
      "bao-cao.get",
    ],
  },
  {
    name: "manager",
    description: "Quản lý vận hành hằng ngày — món ăn, bàn, đơn hàng, khuyến mãi, ca làm việc.",
    permissions: [
      "dashboard.get",
      "mon-an.get",
      "mon-an.tao",
      "mon-an.sua",
      "mon-an.xoa",
      "mon-an.danh-muc",
      "ban.get",
      "ban.tao",
      "ban.sua",
      "ban.xoa",
      "ban.khu-vuc",
      "don-hang.get",
      "don-hang.thanh-toan",
      "don-hang.huy",
      "don-hang.xoa-mon",
      "don-hang.khuyen-mai",
      "khuyen-mai.get",
      "khuyen-mai.tao",
      "khuyen-mai.sua",
      "khuyen-mai.xoa",
      "ca-lam-viec.get",
      "ca-lam-viec.mo-dong",
      "may-in.get",
      "may-in.tao",
      "may-in.sua",
      "may-in.xoa",
      "may-in.quet-mang",
      "thanh-toan.get",
    ],
  },
  {
    name: "admin",
    description: "Toàn quyền vận hành + cấu hình hệ thống, người dùng, báo cáo, trợ lý AI.",
    permissions: [
      "dashboard.get",
      "mon-an.get",
      "mon-an.tao",
      "mon-an.sua",
      "mon-an.xoa",
      "mon-an.danh-muc",
      "ban.get",
      "ban.tao",
      "ban.sua",
      "ban.xoa",
      "ban.khu-vuc",
      "don-hang.get",
      "don-hang.thanh-toan",
      "don-hang.huy",
      "don-hang.xoa-mon",
      "don-hang.khuyen-mai",
      "khuyen-mai.get",
      "khuyen-mai.tao",
      "khuyen-mai.sua",
      "khuyen-mai.xoa",
      "ca-lam-viec.get",
      "ca-lam-viec.mo-dong",
      "may-in.get",
      "may-in.tao",
      "may-in.sua",
      "may-in.xoa",
      "may-in.quet-mang",
      "thanh-toan.get",
      "thanh-toan.sua",
      "bao-cao.get",
      "nguoi-dung.get",
      "nguoi-dung.tao",
      "nguoi-dung.gan-vai-tro",
      "nguoi-dung.khoa-mo-khoa",
      "nguoi-dung.doi-mat-khau",
      "vai-tro.get",
      "vai-tro.tao",
      "vai-tro.sua",
      "vai-tro.xoa",
      "tro-ly-ai.get",
      "tro-ly-ai.su-dung",
      "tro-ly-ai.doi-ten",
      "tro-ly-ai.xoa-phien",
      "tro-ly-ai-thong-ke.get",
    ],
  },
];
